import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs/promises';import path from'node:path';import os from'node:os';import{createRequire}from'node:module';
import{curve,evaluate,boneMatrices,point,Renderer}from'../src/index.mjs';import{deformVertices,solveRig}from'../src/character.mjs';import{readProject,editProject,restoreRevision,compileProject,importAsset,renderJob,atomic}from'../src/production.mjs';import{dispatch}from'../src/agent-api.mjs';
const require=createRequire(import.meta.url),platform=require('@napi-rs/canvas');
const project=()=>({version:1,width:64,height:64,fps:2,duration:1,nodes:[{id:'actor',type:'rect',width:20,height:20,fill:'#f00'}]});
async function fixture(t,p=project()){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'code-brush-test-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'film.json');await fs.writeFile(file,JSON.stringify(p));return{file,dir};}
test('bezier easing preserves endpoints and custom timing',()=>{assert.ok(curve({type:'bezier',x1:.4,y1:0,x2:.8,y2:1},.5)<.5);assert.ok(Math.abs(curve({type:'bezier',x1:0,y1:0,x2:1,y2:1},.5)-.5)<1e-8);});
test('sparse facial poses combine additively without mutating source',()=>{const p=project();Object.assign(p.nodes[0],{x:5,poses:{smile:{x:20},squint:{x:-4}},poseWeights:{smile:.5,squint:.5}});assert.equal(evaluate(p,0).nodes[0].x,13);assert.equal(p.nodes[0].x,5);});
test('corrective shapes and lattice deformation combine',()=>{const node={vertices:[[.5,.5]],shapeKeys:{lift:[[0,1]]},shapeWeights:{lift:.5},lattice:{columns:1,rows:1,bounds:[0,0,1,1],offsets:[[1,0],[1,0],[1,0],[1,0]]}};assert.deepEqual(deformVertices(node),[[1.5,1]]);});
test('CCD chain reaches target and obeys local limits',()=>{const bones=[{id:'a',length:30},{id:'b',parent:'a',x:30,length:25},{id:'c',parent:'b',x:25,length:15}];const result=solveRig(bones,[{type:'ik',chain:['a','b','c'],target:[35,35],iterations:100}]),m=boneMatrices(result),tip=point(m.c,[15,0]);assert.ok(Math.hypot(tip[0]-35,tip[1]-35)<.1);const limited=solveRig([{id:'a',length:20,limits:[-10,10]}],[{type:'lookAt',bone:'a',target:[0,20]}]);assert.equal(limited[0].rotation,10);});
test('isolated opacity does not darken overlapping children twice',()=>{const p=project();p.nodes=[{id:'g',type:'group',isolated:true,opacity:.5,children:[{id:'a',type:'rect',width:40,height:40,fill:'#f00'},{id:'b',type:'rect',width:40,height:40,fill:'#f00'}]}];const c=platform.createCanvas(64,64);new Renderer(platform).render(c.getContext('2d'),p,0,{background:false});const pixel=c.getContext('2d').getImageData(10,10,1,1).data;assert.ok(pixel[3]>=127&&pixel[3]<=128);});
test('alpha masks crop group content',()=>{const p=project();p.nodes=[{id:'g',type:'group',children:[{id:'a',type:'rect',width:60,height:60,fill:'#f00'}],mask:{id:'m',type:'rect',width:20,height:60,fill:'#fff'}}];const c=platform.createCanvas(64,64);new Renderer(platform).render(c.getContext('2d'),p,0,{background:false});assert.equal(c.getContext('2d').getImageData(10,10,1,1).data[3],255);assert.equal(c.getContext('2d').getImageData(30,10,1,1).data[3],0);});
test('stale revisions cannot overwrite newer edits',async t=>{const{file}=await fixture(t),r=await readProject(file);await editProject(file,[{op:'set',target:'actor',property:'x',value:30}],r.revision);await assert.rejects(editProject(file,[{op:'set',target:'actor',property:'x',value:40}],r.revision),/REVISION_CONFLICT/);assert.equal((await readProject(file)).project.nodes[0].x,30);});
test('failed transactions leave file unchanged and release lock',async t=>{const{file}=await fixture(t),r=await readProject(file);await assert.rejects(editProject(file,[{op:'add',node:{id:'actor',type:'rect'}}],r.revision));assert.equal((await readProject(file)).revision,r.revision);await editProject(file,[{op:'set',target:'actor',property:'x',value:1}],r.revision);});
test('restore removes properties introduced after a snapshot',async t=>{const{file}=await fixture(t),r=await readProject(file);await editProject(file,[{op:'set',target:'project',property:'newField',value:1}],r.revision);const now=await readProject(file);await restoreRevision(file,r.revision,now.revision);assert.equal((await readProject(file)).project.newField,undefined);});
test('instances namespace character drawings and tracks',async t=>{const{file,dir}=await fixture(t);await fs.writeFile(path.join(dir,'character.json'),JSON.stringify({nodes:[{id:'face',type:'drawing',drawing:'smile'}],drawings:{smile:[{id:'mouth',type:'rect',fill:'#f00'}]},tracks:[{target:'face',property:'x',keys:[[0,0],[1,10]]}]}));const p=project();p.characters={bear:'character.json'};p.nodes=[{id:'one',type:'instance',character:'bear'},{id:'two',type:'instance',character:'bear'}];const out=await compileProject(p,file);assert.equal(out.nodes[0].children[0].drawing,'one.smile');assert.ok(out.drawings['two.smile']);assert.equal(out.tracks[1].target,'two.face');});
test('asset import records hash and preserves image bytes',async t=>{const{file,dir}=await fixture(t),c=platform.createCanvas(8,8);const source=path.join(dir,'source.png');await fs.writeFile(source,c.toBuffer('image/png'));const r=await importAsset(file,{id:'art',source,kind:'image',provenance:'test'});assert.equal(r.assets[0].sha256.length,64);assert.deepEqual(await fs.readFile(path.join(dir,r.assets[0].path)),await fs.readFile(source));});
test('render cache resumes and invalidates when project changes',async t=>{const{file}=await fixture(t);const first=await renderJob(file),second=await renderJob(file);assert.equal(first.cached,0);assert.equal(second.cached,2);const r=await readProject(file);await editProject(file,[{op:'set',target:'actor',property:'fill',value:'#00f'}],r.revision);const third=await renderJob(file);assert.equal(third.cached,0);assert.notEqual(third.key,first.key);});
test('remove prunes descendant animation tracks',async t=>{const p=project();p.nodes=[{id:'group',type:'group',children:p.nodes}];p.tracks=[{target:'actor',property:'x',keys:[[0,0],[1,5]]}];const{file}=await fixture(t,p);await editProject(file,[{op:'remove',target:'group'}]);assert.equal((await readProject(file)).project.tracks.length,0);});
