#!/usr/bin/env node
import fs from'node:fs/promises';import path from'node:path';import{createRequire}from'node:module';import{pathToFileURL}from'node:url';import{spawn}from'node:child_process';import{once}from'node:events';import http from'node:http';
import{Renderer,validate,evaluate,indexNodes,setProperty}from'./index.mjs';import{audioGraph}from'./audio.mjs';
const require=createRequire(import.meta.url),platform=require('@napi-rs/canvas');
const args=process.argv.slice(2),cmd=args.shift(),arg=args.shift();const opt=(k,d)=>{const i=args.indexOf('--'+k);return i<0?d:args[i+1];};
async function load(file){const p=JSON.parse(await fs.readFile(file,'utf8'));validate(p);const assets={};for(const[k,v]of Object.entries(p.assets??{}))assets[k]=await platform.loadImage(path.resolve(path.dirname(file),v));let plugins={};if(p.plugin)plugins=(await import(pathToFileURL(path.resolve(path.dirname(file),p.plugin)))).default;return{p,renderer:new Renderer(platform,assets,plugins)};}
async function main(){
 if(!cmd||cmd==='help'){console.log('code-brush init PROJECT.json\ncode-brush inspect PROJECT.json [--time 1] [--node id]\ncode-brush set PROJECT.json --node id --property rotation --value 30\ncode-brush key PROJECT.json --node id --property rotation --time 2 --value 45\ncode-brush frame PROJECT.json --time 2 --out frame.png\ncode-brush contact PROJECT.json --out contact.png\ncode-brush render PROJECT.json --out film.mp4 [--width 1920]\ncode-brush preview PROJECT.json [--port 8080]\ncode-brush validate PROJECT.json\ncode-brush blender scene.blend --out output/frame_ [--start 1 --end 240]');return;}
 if(!arg)throw Error('Missing project path');
 if(cmd==='init'){await fs.writeFile(arg,JSON.stringify({version:1,title:'Untitled film',width:1920,height:1080,fps:24,duration:10,background:'#e9e1cc',assets:{},drawings:{},nodes:[{id:'subject',type:'ellipse',x:400,y:540,rx:60,ry:90,fill:'#b86543'}],tracks:[{target:'subject',property:'x',keys:[[0,400],[10,1500,'smooth']]}],shots:[{id:'shot-01',start:0,end:10}]},null,2),{flag:'wx'});console.log(arg);return;}
 if(cmd==='blender'){const child=spawn('blender',['-b',path.resolve(arg),'-o',path.resolve(opt('out','output/frame_')),'-F','PNG','-s',opt('start','1'),'-e',opt('end','240'),'-a'],{stdio:'inherit'});const result=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve);});if(result)throw Error('Blender render failed');return;}
 const file=path.resolve(arg),p=JSON.parse(await fs.readFile(file,'utf8'));
 if(cmd==='validate'){console.log(JSON.stringify(validate(p),null,2));return;}
 if(cmd==='inspect'){validate(p);const state=evaluate(p,Number(opt('time',0))),id=opt('node',null);console.log(JSON.stringify(id?indexNodes(state.nodes).get(id):{...validate(p),title:p.title,shot:state.currentShot,camera:state.camera,nodes:[...indexNodes(state.nodes).values()].map(n=>({id:n.id,type:n.type}))},null,2));return;}
 if(cmd==='set'||cmd==='key'){
  const id=opt('node'),property=opt('property');if(!id||!property)throw Error('--node and --property required');const value=JSON.parse(opt('value'));const target=id==='camera'?(p.camera??={}):indexNodes(p.nodes).get(id);if(!target)throw Error('Unknown node '+id);
  if(cmd==='set')setProperty(target,property,value);else{const t=Number(opt('time'));if(!Number.isFinite(t))throw Error('--time required');p.tracks??=[];let tr=p.tracks.find(k=>k.target===id&&k.property===property);if(!tr){tr={target:id,property,keys:[]};p.tracks.push(tr);}const key=tr.keys.find(k=>k[0]===t);if(key){key[1]=value;key[2]=opt('ease','smooth');}else tr.keys.push([t,value,opt('ease','smooth')]);tr.keys.sort((a,b)=>a[0]-b[0]);}
  validate(p);const temp=file+'.tmp';await fs.writeFile(temp,JSON.stringify(p,null,2));await fs.rename(temp,file);console.log('Updated '+file);return;
 }
 const{renderer}=await load(file);
 if(cmd==='preview'){
  const make=t=>{const cv=platform.createCanvas(960,Math.round(960*p.height/p.width));renderer.render(cv.getContext('2d'),p,t,{guides:true});return cv.toBuffer('image/png');};
  const html=`<!doctype html><meta name="viewport" content="width=device-width"><title>Code-Brush shot inspector</title><style>body{background:#16211f;color:#e8e1c7;font:16px system-ui;max-width:1200px;margin:32px auto;padding:20px}img{width:100%;display:block}input{width:100%;accent-color:#dbad66}button{padding:10px;background:#dbad66;border:0;border-radius:5px;margin:12px 8px 12px 0}small{color:#a0b3a5}</style><h1>Code-Brush / Shot inspector</h1><small>Rendered poses with rig guides. Use an encoded render to review real-time motion and sound.</small><img id="frame" src="/frame?t=0"><button id="prev">Previous frame</button><button id="next">Next frame</button><span id="time">0</span><input id="scrub" type="range" min="0" max="${p.duration-1/p.fps}" step="${1/p.fps}" value="0"><script>let sequence=0;async function show(){const token=++sequence,t=+scrub.value;time.textContent=t.toFixed(3)+'s';const b=await(await fetch('/frame?t='+t)).blob();if(token!==sequence)return;const u=URL.createObjectURL(b),old=frame.src;frame.src=u;if(old.startsWith('blob:'))URL.revokeObjectURL(old);}scrub.oninput=show;prev.onclick=()=>{scrub.value=Math.max(0,+scrub.value-${1/p.fps});show()};next.onclick=()=>{scrub.value=Math.min(${p.duration-1/p.fps},+scrub.value+${1/p.fps});show()};</script>`;
  http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/frame'){const t=Number(u.searchParams.get('t'));if(!Number.isFinite(t))throw Error('Invalid time');res.writeHead(200,{'Content-Type':'image/png'});res.end(make(t));}else{res.writeHead(200,{'Content-Type':'text/html'});res.end(html);}}catch(e){res.writeHead(400);res.end(e.message);}}).listen(Number(opt('port',8080)),'127.0.0.1',()=>console.log('Inspector http://localhost:'+opt('port',8080)));return;
 }
 const width=Number(opt('width',p.width)),height=Math.round(width*p.height/p.width/2)*2;if(!(width>0)||width%2)throw Error('width must be positive and even');const can=platform.createCanvas(width,height),c=can.getContext('2d');const out=path.resolve(opt('out',`output/${cmd==='render'?'film.mp4':cmd==='contact'?'contact.png':'frame.png'}`));await fs.mkdir(path.dirname(out),{recursive:true});
 if(cmd==='frame'){renderer.render(c,p,Number(opt('time',0)),{guides:args.includes('--guides')});await fs.writeFile(out,can.toBuffer('image/png'));console.log(out);return;}
 if(cmd==='contact'){const cols=3,rows=3,tw=480,th=Math.round(tw*p.height/p.width),sheet=platform.createCanvas(cols*tw,rows*(th+30)),s=sheet.getContext('2d');s.fillStyle='#17241e';s.fillRect(0,0,sheet.width,sheet.height);for(let i=0;i<9;i++){const t=i*(p.duration-1/p.fps)/8;renderer.render(c,p,t);const x=i%3*tw,y=Math.floor(i/3)*(th+30);s.drawImage(can,x,y,tw,th);s.fillStyle='#f0e4c9';s.font='16px sans-serif';s.fillText(t.toFixed(2)+'s',x+12,y+th+22);}await fs.writeFile(out,sheet.toBuffer('image/png'));console.log(out);return;}
 if(cmd!=='render')throw Error('Unknown command '+cmd);
 const a=['-y','-f','rawvideo','-pixel_format','rgba','-video_size',`${width}x${height}`,'-framerate',String(p.fps),'-i','pipe:0'];const audio=audioGraph(p,path.dirname(file));a.push(...audio.inputs);if(audio.enabled)a.push('-filter_complex',audio.filters,'-map','0:v:0','-map','[mix]');a.push('-c:v','libx264','-preset','medium','-crf','18','-pix_fmt','yuv420p');if(audio.enabled)a.push('-c:a','aac','-b:a','192k');a.push('-t',String(p.duration),'-movflags','+faststart',out);
 const ff=spawn('ffmpeg',a,{stdio:['pipe','ignore','pipe']});let log='';ff.stderr.on('data',b=>log=(log+b).slice(-6000));ff.stdin.on('error',()=>{});const done=once(ff,'close');for(let i=0;i<Math.round(p.duration*p.fps);i++){renderer.render(c,p,i/p.fps);if(!ff.stdin.write(can.data()))await Promise.race([once(ff.stdin,'drain'),done.then(()=>{throw Error(log);})]);if(i%p.fps===0)console.log('frame '+i);}ff.stdin.end();const[code]=await done;if(code)throw Error(log);console.log(out);
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
